[package]
name = "kademlia-exporter"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.0"
env_logger = "0.7.1"
futures = "0.3.1"
libp2p = "0.18.0"
libp2p-kad = "0.18.0"
log = "0.4.1"
prometheus = "0.7"
void = "1.0.2"
tide = "0.6"
exit-future = "0.2"
ctrlc = "3"
structopt = "0.3"
futures-timer = "3"

