[package]
name = "kad-exporter"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.0"
env_logger = "0.7.1"
futures = "0.3.1"
libp2p = "0.16.2"
libp2p-kad = "0.16.2"
prometheus = "0.7"
void = "1.0.2"
tide = "*"

