[package]
name = "kademlia-exporter"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.4"
cidr = "0.1.1"
csv = "1.1.3"
env_logger = "0.7.1"
futures = "0.3.5"
libp2p = { version = "0.28.1", default-features = false, features = ["dns", "noise", "tcp-async-std", "yamux", "identify", "kad", "ping", "mplex"] }
log = "0.4.11"
prometheus = "0.10.0"
void = "1.0.2"
tide = "0.13.0"
exit-future = "0.2.0"
ctrlc = "3.1.6"
structopt = "0.3.18"
futures-timer = "3.0.2"
maxminddb = "0.14.0"
serde = "1.0.116"
serde_derive = "1.0.115"
toml = "0.5.6"

# [patch."https://github.com/mxinden/rust-libp2p"]
# libp2p = { path = "/home/mxinden/code/github.com/libp2p/rust-libp2p" }
# libp2p-kad = { path = "/home/mxinden/code/github.com/libp2p/rust-libp2p/protocols/kad" }

