[package]
name = "kad-exporter"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.0"
env_logger = "0.7.1"
futures = "0.3.1"
libp2p = { path = "../../libp2p/rust-libp2p" }
libp2p-kad = { git = "https://github.com/libp2p/rust-libp2p.git", branch = "stable-futures" }
void = "1.0.2"

